export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    teamChats: ['team-chats'] as const,
    teamChat: (teamChatId: string) => ['team-chat', teamChatId] as const,
    teamParticipants: (teamChatId: string) => ['team-chat-participants', teamChatId] as const,
    teamMessages: (teamChatId: string) => ['team-messages', teamChatId] as const,
    teamMessagesAround: (teamChatId: string, messageId: string) => ['team-messages-around', teamChatId, messageId] as const,
    teamMentionRequestsBase: ['team-mention-requests'] as const,
    teamMentionRequests: (teamChatId: string, sessionIds: string[]) => ['team-mention-requests', teamChatId, ...sessionIds] as const,
    sessionTeamMentions: (sessionId: string) => ['session-team-mentions', sessionId] as const,
    sessionTeamMembershipsBase: ['session-team-memberships'] as const,
    sessionTeamMemberships: (sessionId: string) => ['session-team-memberships', sessionId] as const,
    machines: ['machines'] as const,
    machineCodexModels: (machineId: string) => ['machine-codex-models', machineId] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    editorDirectoryBase: (machineId: string) => ['editor', 'directory', machineId] as const,
    editorDirectory: (machineId: string, path: string) => ['editor', 'directory', machineId, path] as const,
    editorFile: (machineId: string, path: string) => ['editor', 'file', machineId, path] as const,
    editorGitStatusBase: (machineId: string, projectPath: string) => ['editor', 'git-status', machineId, projectPath] as const,
    editorGitBranches: (machineId: string, projectPath: string, repoRoot?: string) => ['editor', 'git-branches', machineId, projectPath, repoRoot ?? 'auto'] as const,
    editorGitStashes: (machineId: string, projectPath: string, repoRoot?: string) => ['editor', 'git-stashes', machineId, projectPath, repoRoot ?? 'auto'] as const,
    editorGitStatus: (machineId: string, projectPath: string, repoRoot?: string) => ['editor', 'git-status', machineId, projectPath, repoRoot ?? 'auto'] as const,
    editorGitDiff: (machineId: string, projectPath: string, filePath: string, staged?: boolean, repoRoot?: string) => ['editor', 'git-diff', machineId, projectPath, repoRoot ?? 'auto', filePath, staged ? 'staged' : 'unstaged'] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    sessionCodexModels: (sessionId: string) => ['session-codex-models', sessionId] as const,
    sessionOpencodeModels: (sessionId: string) => ['session-opencode-models', sessionId] as const,
    machineOpencodeModelsForCwd: (machineId: string, cwd: string) => ['machine-opencode-models', machineId, cwd] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
}
