import { Database } from 'bun:sqlite'
import { describe,expect,it } from 'bun:test'
import { SharedHubStore } from '../store/sharedHubStore'
import { RunnerEnrollmentService } from './runnerEnrollmentService'
import { RunnerLifecycleService } from './runnerLifecycleService'
import { RunnerAuthenticator } from '../auth/runnerAuthenticator'

describe('Runner lifecycle',()=>{it('CAS rotates once, revoke releases claims, and same profile re-enrolls',()=>{const db=new Database(':memory:');const store=new SharedHubStore(db,{organizationId:'o1',organizationName:'Pilot'});db.exec("INSERT INTO memberships(id,organization_id,invited_email,role,status,created_at) VALUES('u1','o1','u@example.com','admin','active',1)");let now=1000;const subject={membershipId:'u1',organizationId:'o1',role:'admin' as const,disabled:false};const enrollment=new RunnerEnrollmentService(store,'pepper','https://hub.test',()=>now);const lifecycle=new RunnerLifecycleService(store,'pepper',()=>++now);const auth=new RunnerAuthenticator(store,'pepper');const issued=enrollment.issue(subject,'u1');const first=enrollment.exchange({code:issued.code,profile:'p1',machine:{id:'m1',name:'M',platform:'linux',arch:'x64'}});const rotated=lifecycle.rotate(subject,first.runnerId,1);expect(auth.authenticate('o1',first.credential)).toBeNull();expect(auth.authenticate('o1',rotated.credential)?.id).toBe(first.runnerId);expect(()=>lifecycle.rotate(subject,first.runnerId,1)).toThrow('conflict');lifecycle.revoke(subject,first.runnerId);expect(lifecycle.revoke(subject,first.runnerId)).toEqual({runnerId:first.runnerId,revoked:true});expect(auth.authenticate('o1',rotated.credential)).toBeNull();const next=enrollment.issue(subject,'u1');expect(enrollment.exchange({code:next.code,profile:'p1',machine:{id:'m1',name:'M2',platform:'linux',arch:'x64'}}).runnerId).not.toBe(first.runnerId);expect(store.findRunner('o1',first.runnerId)?.status).toBe('revoked');expect(db.prepare('SELECT count(*) count FROM runner_tombstones WHERE runner_id=?').get(first.runnerId)).toEqual({count:1})})})

it('rejects archived revoke without lifecycle mutations',()=>{const db=new Database(':memory:');const store=new SharedHubStore(db,{organizationId:'o1',organizationName:'Pilot'});db.exec("INSERT INTO memberships(id,organization_id,invited_email,role,status,created_at) VALUES('u1','o1','u@example.com','admin','active',1)");store.createRunnerProjection({runnerId:'r1',organizationId:'o1',ownerMembershipId:'u1',machineId:'m1',profile:'p1',name:'M',metadata:{},runnerState:{},createdAt:1});db.exec("UPDATE runners SET status='archived' WHERE id='r1'");const service=new RunnerLifecycleService(store,'pepper',()=>2);expect(()=>service.revoke({membershipId:'u1',organizationId:'o1',role:'admin',disabled:false},'r1')).toThrow('not_found');expect(db.prepare('SELECT count(*) count FROM runner_tombstones').get()).toEqual({count:0});expect(db.prepare('SELECT count(*) count FROM runner_active_claims').get()).toEqual({count:1})})

it('transfers runner ownership and prevents non-owner transfer',()=>{const db=new Database(':memory:');const store=new SharedHubStore(db,{organizationId:'o1',organizationName:'Pilot'});db.exec("INSERT INTO memberships(id,organization_id,invited_email,role,status,created_at) VALUES('u1','o1','a@example.com','admin','active',1),('u2','o1','b@example.com','member','active',1)");store.createRunnerProjection({runnerId:'r1',organizationId:'o1',ownerMembershipId:'u1',machineId:'m1',profile:'p1',name:'M',metadata:{},runnerState:{},createdAt:1});const service=new RunnerLifecycleService(store,'pepper',()=>10);const admin={membershipId:'u1',organizationId:'o1',role:'admin' as const,disabled:false};const member={membershipId:'u2',organizationId:'o1',role:'member' as const,disabled:false};expect(()=>service.transfer(member,'r1','u2')).toThrow('forbidden');const result=service.transfer(admin,'r1','u2');expect(result).toEqual({runnerId:'r1',previousOwnerMembershipId:'u1',newOwnerMembershipId:'u2'});expect(store.findRunner('o1','r1')?.ownerMembershipId).toBe('u2');expect(()=>service.transfer(admin,'r1','u2')).toThrow('conflict')})

it('cleans runner tombstone and authorizes owner',()=>{const db=new Database(':memory:');const store=new SharedHubStore(db,{organizationId:'o1',organizationName:'Pilot'});db.exec("INSERT INTO memberships(id,organization_id,invited_email,role,status,created_at) VALUES('u1','o1','a@example.com','admin','active',1)");store.createRunnerProjection({runnerId:'r1',organizationId:'o1',ownerMembershipId:'u1',machineId:'m1',profile:'p1',name:'M',metadata:{},runnerState:{},createdAt:1});const service=new RunnerLifecycleService(store,'pepper',()=>10);const admin={membershipId:'u1',organizationId:'o1',role:'admin' as const,disabled:false};service.revoke(admin,'r1');expect(service.cleanup(admin,'r1')).toEqual({runnerId:'r1',cleaned:true});expect(()=>service.cleanup(admin,'r1')).toThrow('not_found')})

it('lists runners for admin only',()=>{const db=new Database(':memory:');const store=new SharedHubStore(db,{organizationId:'o1',organizationName:'Pilot'});db.exec("INSERT INTO memberships(id,organization_id,invited_email,role,status,created_at) VALUES('u1','o1','a@example.com','admin','active',1),('u2','o1','b@example.com','member','active',1)");store.createRunnerProjection({runnerId:'r1',organizationId:'o1',ownerMembershipId:'u1',machineId:'m1',profile:'p1',name:'M',metadata:{},runnerState:{},createdAt:1});const service=new RunnerLifecycleService(store,'pepper',()=>10);expect(()=>service.list({membershipId:'u2',organizationId:'o1',role:'member',disabled:false})).toThrow('forbidden');expect(service.list({membershipId:'u1',organizationId:'o1',role:'admin',disabled:false})).toHaveLength(1)})

it('disconnects a Runner only after revoke commits',()=>{const db=new Database(':memory:');const store=new SharedHubStore(db,{organizationId:'o1',organizationName:'Pilot'});db.exec("INSERT INTO memberships(id,organization_id,invited_email,role,status,created_at) VALUES('u1','o1','a@example.com','admin','active',1)");store.createRunnerProjection({runnerId:'r1',organizationId:'o1',ownerMembershipId:'u1',machineId:'m1',profile:'p1',name:'M',metadata:{},runnerState:{},createdAt:1});const calls:string[]=[];const service=new RunnerLifecycleService(store,'pepper',()=>10,(organizationId,runnerId)=>calls.push(`${organizationId}:${runnerId}:${store.findRunner(organizationId,runnerId)?.status}`));service.revoke({membershipId:'u1',organizationId:'o1',role:'admin',disabled:false},'r1');expect(calls).toEqual(['o1:r1:revoked'])})
