import { randomUUID } from 'node:crypto'
import type { AuthorizationSubject } from '../auth/authorizationService'
import { keyedHash, randomOpaqueToken } from '../auth/identityCrypto'
import { SharedHubStore } from '../store/sharedHubStore'
import { RunnerEnrollmentError } from './runnerEnrollmentService'

export class RunnerLifecycleService {
    constructor(private readonly store:SharedHubStore,private readonly pepper:string,private readonly now=()=>Date.now(),private readonly onRevoked?:(organizationId:string,runnerId:string)=>void){}
    private authorize(subject:AuthorizationSubject,runnerId:string,requireActive=true){const runner=this.store.findRunner(subject.organizationId,runnerId);if(!runner||(requireActive&&runner.status!=='active'))throw new RunnerEnrollmentError('not_found');if(subject.disabled||(subject.role!=='admin'&&runner.ownerMembershipId!==subject.membershipId))throw new RunnerEnrollmentError('forbidden');return runner}
    list(subject:AuthorizationSubject){if(subject.disabled||subject.role!=='admin')throw new RunnerEnrollmentError('forbidden');return this.store.listRunners(subject.organizationId)}
    rotate(subject:AuthorizationSubject,runnerId:string,expectedGeneration:number){this.authorize(subject,runnerId);const secret=randomOpaqueToken(48),credentialId=randomUUID(),now=this.now();return this.store.transaction(()=>{const result=this.store.rotateRunnerCredential({organizationId:subject.organizationId,runnerId,expectedGeneration,id:credentialId,secretHash:keyedHash(secret,this.pepper),now});if(result==='not_found')throw new RunnerEnrollmentError('not_found');if(result==='conflict')throw new RunnerEnrollmentError('conflict');this.store.appendAuditEvent({id:randomUUID(),organizationId:subject.organizationId,actorType:'user',actorId:subject.membershipId,action:'runner.credential.rotate',resourceType:'runner',resourceId:runnerId,outcome:'success',createdAt:now});return{runnerId,credential:{credentialId,secret},generation:expectedGeneration+1}})}
    revoke(subject:AuthorizationSubject,runnerId:string){this.authorize(subject,runnerId,false);const now=this.now();const value=this.store.transaction(()=>{const result=this.store.revokeRunnerAccess({organizationId:subject.organizationId,runnerId,now});if(result==='not_found')throw new RunnerEnrollmentError('not_found');if(result==='already_revoked')return{runnerId,revoked:true as const};this.store.appendAuditEvent({id:randomUUID(),organizationId:subject.organizationId,actorType:'user',actorId:subject.membershipId,action:'runner.revoke',resourceType:'runner',resourceId:runnerId,outcome:'success',createdAt:now});this.store.appendOutboxEvent({id:randomUUID(),organizationId:subject.organizationId,name:'runner.revoked',resourceType:'runner',resourceId:runnerId,createdAt:now});return{runnerId,revoked:true as const}});this.onRevoked?.(subject.organizationId,runnerId);return value}
    transfer(subject:AuthorizationSubject,runnerId:string,targetMembershipId:string){this.authorize(subject,runnerId);const now=this.now();return this.store.transaction(()=>{const runner=this.store.findRunner(subject.organizationId,runnerId);if(!runner)throw new RunnerEnrollmentError('not_found');const result=this.store.transferRunnerOwnership(subject.organizationId,runnerId,targetMembershipId);if(result==='not_found')throw new RunnerEnrollmentError('not_found');if(result==='same_owner')throw new RunnerEnrollmentError('conflict');if(result==='target_not_found')throw new RunnerEnrollmentError('not_found');this.store.appendAuditEvent({id:randomUUID(),organizationId:subject.organizationId,actorType:'user',actorId:subject.membershipId,action:'runner.transfer',resourceType:'runner',resourceId:runnerId,outcome:'success',createdAt:now});this.store.appendOutboxEvent({id:randomUUID(),organizationId:subject.organizationId,name:'runner.transferred',resourceType:'runner',resourceId:runnerId,createdAt:now});return{runnerId,previousOwnerMembershipId:runner.ownerMembershipId,newOwnerMembershipId:targetMembershipId}})}
    cleanup(subject:AuthorizationSubject,runnerId:string){this.authorize(subject,runnerId,false);const now=this.now();const result=this.store.cleanupRunnerTombstone(subject.organizationId,runnerId);if(result==='not_found')throw new RunnerEnrollmentError('not_found');this.store.appendOutboxEvent({id:randomUUID(),organizationId:subject.organizationId,name:'runner.cleaned',resourceType:'runner',resourceId:runnerId,createdAt:now});return{runnerId,cleaned:true as const}}
}
