import { Hono, type Context } from 'hono'
import { RunnerCleanupResultSchema, RunnerCredentialRotateResultSchema, RunnerCredentialRotateSchema, RunnerEnrollmentExchangeSchema, RunnerEnrollmentIssueResultSchema, RunnerEnrollmentIssueSchema, RunnerEnrollmentListResultSchema, RunnerEnrollmentResultSchema, RunnerListResultSchema, RunnerRevocationResultSchema, RunnerTransferResultSchema, RunnerTransferSchema } from '@hapi/protocol/runner-enrollment'
import type { SharedWebAppEnv } from '../sharedAuthEnv'
import { RunnerEnrollmentError, RunnerEnrollmentService } from '../../application/runnerEnrollmentService'
import { RunnerLifecycleService } from '../../application/runnerLifecycleService'

export function createRunnerExchangeRoutes(service:RunnerEnrollmentService){const app=new Hono();app.post('/runner-enrollments/exchange',async(c)=>{const body=await parse(c.req.raw,RunnerEnrollmentExchangeSchema);if(!body.ok)return invalid(c);return handle(c,()=>{c.header('Cache-Control','no-store');return c.json(RunnerEnrollmentResultSchema.parse(service.exchange(body.value)),201)})});return app}

export function createRunnerEnrollmentRoutes(enrollment:RunnerEnrollmentService,lifecycle:RunnerLifecycleService){const app=new Hono<SharedWebAppEnv>();app.post('/runner-enrollments',async(c)=>{const body=await parse(c.req.raw,RunnerEnrollmentIssueSchema);if(!body.ok)return invalid(c);return handle(c,()=>{c.header('Cache-Control','no-store');return c.json(RunnerEnrollmentIssueResultSchema.parse(enrollment.issue(subject(c),body.value.ownerMembershipId)),201)})});app.get('/runner-enrollments',(c)=>handle(c,()=>c.json(RunnerEnrollmentListResultSchema.parse(enrollment.list(subject(c))))));app.delete('/runner-enrollments/:id',(c)=>{if(!validPathId(c.req.param('id')))return invalid(c);return handle(c,()=>{enrollment.cancel(subject(c),c.req.param('id'));return c.body(null,204)})});app.get('/runners',(c)=>handle(c,()=>c.json(RunnerListResultSchema.parse({runners:lifecycle.list(subject(c))}))));app.post('/runners/:id/transfer',async(c)=>{if(!validPathId(c.req.param('id')))return invalid(c);const body=await parse(c.req.raw,RunnerTransferSchema);if(!body.ok)return invalid(c);return handle(c,()=>c.json(RunnerTransferResultSchema.parse(lifecycle.transfer(subject(c),c.req.param('id'),body.value.targetMembershipId))))});app.post('/runners/:id/cleanup',(c)=>{if(!validPathId(c.req.param('id')))return invalid(c);return handle(c,()=>c.json(RunnerCleanupResultSchema.parse(lifecycle.cleanup(subject(c),c.req.param('id')))))});app.post('/runners/:id/credential/rotate',async(c)=>{if(!validPathId(c.req.param('id')))return invalid(c);const body=await parse(c.req.raw,RunnerCredentialRotateSchema);if(!body.ok)return invalid(c);return handle(c,()=>{c.header('Cache-Control','no-store');return c.json(RunnerCredentialRotateResultSchema.parse(lifecycle.rotate(subject(c),c.req.param('id'),body.value.expectedGeneration)))})});app.post('/runners/:id/revoke',(c)=>{if(!validPathId(c.req.param('id')))return invalid(c);return handle(c,()=>c.json(RunnerRevocationResultSchema.parse(lifecycle.revoke(subject(c),c.req.param('id')))))});return app}

function subject(c:Context<SharedWebAppEnv>){return{membershipId:c.get('membershipId'),organizationId:c.get('organizationId'),role:c.get('organizationRole'),disabled:false}}
const MAX_JSON_BODY_BYTES=16*1024
async function parse<T>(request:Request,schema:{safeParse:(value:unknown)=>{success:boolean;data?:T}}):Promise<{ok:true;value:T}|{ok:false}>{const declared=Number(request.headers.get('content-length')??0);if(!Number.isFinite(declared)||declared>MAX_JSON_BODY_BYTES)return{ok:false};const text=await request.text().catch(()=>null);if(text===null||new TextEncoder().encode(text).byteLength>MAX_JSON_BODY_BYTES)return{ok:false};let value:unknown;try{value=JSON.parse(text)}catch{return{ok:false}}const parsed=schema.safeParse(value);return parsed.success?{ok:true,value:parsed.data as T}:{ok:false}}
function validPathId(value:string){return value.length>0&&value.length<=256}
function invalid(c:Context){return c.json({error:'Invalid request.',code:'bad_request'},400)}
function handle<T>(c:Context,operation:()=>T):T|Response{try{return operation()}catch(error){if(error instanceof RunnerEnrollmentError){const status=error.code==='forbidden'?403:error.code==='not_found'?404:409;return c.json({error:'Runner enrollment request failed.',code:error.code},status)}return c.json({error:'Runner enrollment request failed.',code:'internal_error'},500)}}
