import { expect,it } from 'bun:test'
import { createRunnerEnrollmentRoutes, createRunnerExchangeRoutes } from './runnerEnrollments'

it('validates service responses and sanitizes unknown failures',async()=>{const invalid=createRunnerExchangeRoutes({exchange:()=>({secretHash:'leak'})} as never);const body=JSON.stringify({code:'0123456789abcdef',profile:'p',machine:{id:'m',name:'M',platform:'linux',arch:'x64'}});const request=()=>new Request('http://x/runner-enrollments/exchange',{method:'POST',headers:{'content-type':'application/json'},body});const bad=await invalid.fetch(request());expect(bad.status).toBe(500);expect(await bad.text()).not.toContain('secretHash');const unknown=createRunnerExchangeRoutes({exchange:()=>{throw new Error('/private/path secret-value')}} as never);const response=await unknown.fetch(request());expect(response.status).toBe(500);expect(await response.text()).toBe('{"error":"Runner enrollment request failed.","code":"internal_error"}')})

it('bounds public bodies and marks secret exchange responses no-store',async()=>{const app=createRunnerExchangeRoutes({exchange:()=>({organizationId:'o1',runnerId:'r1',credential:{credentialId:'c1',secret:'x'.repeat(32)},generation:1,hubUrl:'https://hub.test'})} as never);const oversized=await app.request('/runner-enrollments/exchange',{method:'POST',headers:{'content-type':'application/json'},body:' '.repeat(16*1024+1)});expect(oversized.status).toBe(400);const ok=await app.request('/runner-enrollments/exchange',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:'0123456789abcdef',profile:'p',machine:{id:'m',name:'M',platform:'linux',arch:'x64'}})});expect(ok.headers.get('cache-control')).toBe('no-store')})

it('bounds path ids and marks issue/rotate secrets no-store',async()=>{const app=createRunnerEnrollmentRoutes({issue:()=>({enrollmentId:'e1',code:'x'.repeat(16),expiresAt:1}),list:()=>({enrollments:[]}),cancel:()=>{}} as never,{rotate:()=>({runnerId:'r1',credential:{credentialId:'c1',secret:'x'.repeat(32)},generation:2}),revoke:()=>({runnerId:'r1',revoked:true}),list:()=>[],transfer:()=>null as never,cleanup:()=>null as never} as never);const issue=await app.request('/runner-enrollments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ownerMembershipId:'u1'})});expect(issue.headers.get('cache-control')).toBe('no-store');const rotate=await app.request('/runners/r1/credential/rotate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedGeneration:1})});expect(rotate.headers.get('cache-control')).toBe('no-store');expect((await app.request(`/runners/${'x'.repeat(257)}/revoke`,{method:'POST'})).status).toBe(400)})

it('serves the runner list and validates transfer/cleanup routes',async()=>{const app=createRunnerEnrollmentRoutes({issue:()=>({enrollmentId:'e1',code:'x'.repeat(16),expiresAt:1}),list:()=>({enrollments:[]}),cancel:()=>{}} as never,{list:()=>([{id:'r1',organizationId:'o1',ownerMembershipId:'u1',machineId:'m1',profile:'p',name:'M',status:'active',createdAt:1}] as never),transfer:()=>({runnerId:'r1',previousOwnerMembershipId:'u1',newOwnerMembershipId:'u2'}),cleanup:()=>({runnerId:'r1',cleaned:true}),rotate:()=>null as never,revoke:()=>null as never} as never);const list=await app.request('/runners');expect(list.status).toBe(200);const json=await list.json() as {runners:unknown[]};expect(json.runners).toHaveLength(1);const transfer=await app.request('/runners/r1/transfer',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({targetMembershipId:'u2'})});expect(transfer.status).toBe(200);const cleanup=await app.request('/runners/r1/cleanup',{method:'POST'});expect(cleanup.status).toBe(200)})
